require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/StructInheritance:
  Exclude:
    - app/policies/**/*.rb

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb
    - spec/**/*.rb

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - spec/system/**/*.rb

RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*.rb

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/NestedGroups:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

# Use .reduce(:+) to join view elements in helpers.
Performance/Sum:
  Exclude:
    - app/inputs/**/*.rb
    - app/helpers/**/*.rb
