default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: <%= Utils.env_or_credential "rails_template_database_host", "127.0.0.1" %>
  port: <%= Utils.env_or_credential "rails_template_database_port", "3306" %>

development:
  <<: *default
  database: rails_template_development

test:
  <<: *default
  database: rails_template_test

production:
  <<: *default
  database: rails_template_production
  username: rails_template
  password: <%= Utils.env_or_credential "rails_template_database_password", ("" unless Rails.env.production?) %>
